#!/bin/bash

main() {
  for ((i = 0; i < 8; i += 1)); do
    for ((j = 0; j < 8; j += 1)); do
      if is_even $((i + j)); then
        printf '*'
      else
        printf ' '
      fi
    done
    unset -v j

    printf '\n'
  done
  unset -v i
}

is_even() {
  local -ir int=$1
  return $((int % 2))
}

[ "${BASH_SOURCE[0]}" == "$0" ] && main "$@"
